In [101]:
import pandas as pd

In [102]:
df = pd.read_csv('temp_measurements.csv')

In [103]:
df.head()

,location_id,location_name,sensor_id,parameter,unit,value,measurement_timestamp
0,5199863,Kihumo Village || Antenna Array,13691748,pm1,µg/m³,26.3,2026-07-31T21:00:00Z
1,5199863,Kihumo Village || Antenna Array,13691748,pm1,µg/m³,22.2,2026-07-31T22:00:00Z
2,5199863,Kihumo Village || Antenna Array,13691748,pm1,µg/m³,24.2,2026-07-31T23:00:00Z
3,5199863,Kihumo Village || Antenna Array,13691748,pm1,µg/m³,25.2,2026-08-01T00:00:00Z
4,5199863,Kihumo Village || Antenna Array,13691748,pm1,µg/m³,28.7,2026-08-01T01:00:00Z

In [105]:
df.shape

(4860, 7)

In [106]:
df['sensor_id'].nunique()

5

In [120]:
df.groupby("sensor_id").head(2)

,location_id,location_name,sensor_id,parameter,unit,value,measurement_timestamp
0,5199863,Kihumo Village || Antenna Array,13691748,pm1,µg/m³,26.3,2026-07-31T21:00:00Z
1,5199863,Kihumo Village || Antenna Array,13691748,pm1,µg/m³,22.2,2026-07-31T22:00:00Z
972,5199863,Kihumo Village || Antenna Array,13691749,pm25,µg/m³,40.8,2026-07-31T21:00:00Z
973,5199863,Kihumo Village || Antenna Array,13691749,pm25,µg/m³,34.0,2026-07-31T22:00:00Z
1944,5199863,Kihumo Village || Antenna Array,13691750,relativehumidity,%,57.0,2026-07-31T21:00:00Z
1945,5199863,Kihumo Village || Antenna Array,13691750,relativehumidity,%,58.0,2026-07-31T22:00:00Z
2916,5199863,Kihumo Village || Antenna Array,13691751,temperature,c,18.7,2026-07-31T21:00:00Z
2917,5199863,Kihumo Village || Antenna Array,13691751,temperature,c,17.8,2026-07-31T22:00:00Z
3888,5199863,Kihumo Village || Antenna Array,13691752,um003,particles/cm³,1623.0,2026-07-31T21:00:00Z
3889,5199863,Kihumo Village || Antenna Array,13691752,um003,particles/cm³,1206.0,2026-07-31T22:00:00Z